name: Deploy to EC2

on:
  push:
    branches:
      - 'main'

jobs:
  server-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SSH commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script:
            pkill -9 python
            cd Server
            git pull
            nohup python3 -m uvicorn main:app > server_log.log 2>&1 &
